// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kjuFFTSZb8fanzCHT2C1jz
// Component: DJbGaLTtKAR
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Testimonial from "../../Testimonial"; // plasmic-import: E_l1hqcHcA/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_kit_website_components.module.css"; // plasmic-import: kjuFFTSZb8fanzCHT2C1jz/projectcss
import * as sty from "./PlasmicTestimonials.module.css"; // plasmic-import: DJbGaLTtKAR/css

import image17U7CGaQy from "./images/image17.png"; // plasmic-import: U_7c_gaQy/picture
import image39Y1CLdtC5P from "./images/image39.png"; // plasmic-import: Y1cLdtC5p/picture
import image203Ggd3Cmmi from "./images/image20.png"; // plasmic-import: 3GGD3CMMI/picture
import image19TueIhGKhL from "./images/image19.png"; // plasmic-import: tueIhGKhL/picture
import image301QXLsp3Gl from "./images/image30.png"; // plasmic-import: 1qXLsp3Gl/picture
import image22YEtbjfyJ0 from "./images/image22.png"; // plasmic-import: yEtbjfyJ0/picture
import image18VvWfewPgF from "./images/image18.png"; // plasmic-import: VvWfewPgF/picture
import image70LreVgxzrC from "./images/image70.png"; // plasmic-import: lreVgxzrC/picture
import image21Dqmr3K45D from "./images/image21.png"; // plasmic-import: Dqmr3K45D/picture
import image31FgP35C5M from "./images/image31.png"; // plasmic-import: FgP-35c5m/picture
import image41PGoZZ6Ey from "./images/image41.png"; // plasmic-import: pGoZ-z6Ey/picture
import image442XmoUlGl from "./images/image44.png"; // plasmic-import: 2Xmo-UlGL/picture
import image48MvIw252S from "./images/image48.png"; // plasmic-import: MV-iw252s/picture
import image50Tk5CdJrnd from "./images/image50.png"; // plasmic-import: TK5CdJRND/picture
import image58CTc2ZXwO from "./images/image58.png"; // plasmic-import: CTc2zXw-o/picture
import image47Z7Q0WZtnF from "./images/image47.png"; // plasmic-import: z7Q0WZtnF/picture
import image46Zfpl2P14L from "./images/image46.png"; // plasmic-import: Zfpl2p14L/picture
import image26G5JsDdQkx from "./images/image26.png"; // plasmic-import: G5jsDdQkx/picture
import image29WlKi1L4Eq from "./images/image29.png"; // plasmic-import: WlKI1l4eq/picture
import image32RtBuhLfpe from "./images/image32.png"; // plasmic-import: RtBuhLfpe/picture
import image24BrkhP7IR0 from "./images/image24.png"; // plasmic-import: brkhP7iR0/picture
import image23Sd8FqsUf from "./images/image23.png"; // plasmic-import: sd8fqsUf_/picture
import image280CMsqtag4 from "./images/image28.png"; // plasmic-import: 0CMsqtag4/picture
import image25JukHnjBm2 from "./images/image25.png"; // plasmic-import: jukHnjBM2/picture
import image279Uio4NrWb from "./images/image27.png"; // plasmic-import: 9uio4NrWB/picture
import image43Xlpa8IjYv from "./images/image43.png"; // plasmic-import: xlpa8IjYv/picture
import personHkxei5CPu from "./images/person.png"; // plasmic-import: HKXEI5cPu/picture
import image45CZnS6ZLBf from "./images/image45.png"; // plasmic-import: cZnS6zLBf/picture
import image51WcC99HXh from "./images/image51.png"; // plasmic-import: wcC-99HXh/picture
import image57AVfwvYtpk from "./images/image57.png"; // plasmic-import: AVfwvYTPK/picture
import image49S6UJdcNii from "./images/image49.png"; // plasmic-import: S6uJdcNII/picture
import image52WV9THJz5J from "./images/image52.png"; // plasmic-import: wV9tHJz5J/picture

export type PlasmicTestimonials__VariantMembers = {};

export type PlasmicTestimonials__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestimonials__VariantsArgs;
export const PlasmicTestimonials__VariantProps = new Array<VariantPropType>();

export type PlasmicTestimonials__ArgsType = {};
type ArgPropType = keyof PlasmicTestimonials__ArgsType;
export const PlasmicTestimonials__ArgProps = new Array<ArgPropType>();

export type PlasmicTestimonials__OverridesType = {
  root?: p.Flex<"section">;
};

export interface DefaultTestimonialsProps {
  className?: string;
}

function PlasmicTestimonials__RenderFunc(props: {
  variants: PlasmicTestimonials__VariantsArgs;
  args: PlasmicTestimonials__ArgsType;
  overrides: PlasmicTestimonials__OverridesType;
  dataFetches?: PlasmicTestimonials__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"section"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__iWHrw)}
      >
        <Testimonial
          company={"Intuit"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___8Y1T8
              )}
            >
              {"James Armenta"}
            </div>
          }
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__ms2Dl
              )}
            >
              {
                "It’s already been a huge increase in efficiency for me, personally. I’m really looking forward to a huge drop in scope for our tests that require new components (most of them)."
              }
            </div>
          }
          title={"Software Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___4L5)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image17U7CGaQy}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Venturemark"}
          dest={"https://www.producthunt.com/posts/plasmic" as const}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__nArIo
              )}
            >
              {"Marcus Ellison"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__yW51X
              )}
            >
              {
                "Our designer is empowered to instrument pixel perfect, responsive design. And frontend developers can focus less on boilerplate code. From design -> code -> deploy only takes minutes. And the design is pixel perfect. We're now using Plasmic for our entire web app in production."
              }
            </div>
          }
          title={"CEO"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___0FqP8)}
            height={400 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image39Y1CLdtC5P}
            width={400 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Schibsted Group"}
          dest={
            "https://twitter.com/produkhelt/status/1293475542256189441" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___9U8Eh
              )}
            >
              {"@produkthelt"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__gq7IH
              )}
            >
              {
                "Have you checked out @plasmicapp — so far the best design tool for Product design I have used. If you would combine it with Pixelmators unique approach for image manipulation and Figmas vector drawing goodness we would come pretty far to a Product design powerhouse."
              }
            </div>
          }
          title={"Product Designer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__hGjrn)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image203Ggd3Cmmi}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Github"}
          dest={
            "https://twitter.com/colebemis/status/1283913672851517440" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__bm6PT
              )}
            >
              {"Cole Bemis"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___0ZuNz
              )}
            >
              {
                "I had the opportunity to test out an early version of Plasmic and it’s awesome! Excited for the future of this design tool "
              }
            </div>
          }
          title={"Design Systems Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__ema3O)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image19TueIhGKhL}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Zapier"}
          dest={
            "https://twitter.com/the_real_stacie/status/1303853467845292033" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__ytdR5
              )}
            >
              {"Stacie Taylor"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__s8Hj
              )}
            >
              {
                "Watching @yaaang demo quickly creating #react components with ease using his app @plasmicapp for the second time tonight at a @_collab_lab exclusive presentation. AND I’m just as blown away as I was last time! Check out this app, y’all!"
              }
            </div>
          }
          title={"Frontend Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__ptPt7)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image301QXLsp3Gl}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__s9Zv1
              )}
            >
              {"Atalanda"}
            </div>
          }
          dest={"https://twitter.com/six7/status/1283815059035230210" as const}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__i1SR
              )}
            >
              {"Jan Six"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__jZib
              )}
            >
              {
                "After trying out Plasmic for a bit I have to say it's already incredibly advanced. So many features done right - this is what the intersection of design/eng should look like! "
              }
            </div>
          }
          title={"UI Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__dxGna)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image22YEtbjfyJ0}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Intrepid Ventures"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__yuCpK
              )}
            >
              {"Collin Thompson"}
            </div>
          }
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__zPig
              )}
            >
              {
                "This is by far one of the most empowering tools to come out in a while. Week by week it keeps on getting better. If you’re a designer/no coder/visual developer who wants to make world class applications, or a design or development studio looking for a way to serve your clients better, and faster—I highly recommend checking out Plasmic."
              }
            </div>
          }
          title={"CEO"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__h6An2)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image18VvWfewPgF}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"paperfoods.eu"}
          dest={
            "https://twitter.com/marcojelli/status/1362112661081624577" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__vtLsI
              )}
            >
              {"Ernests Elksnis"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__nZbtU
              )}
            >
              {
                "Plasmic is the tool I was looking for for years...the missing link in this universe. This is the reason I learned React. And their support is next-level."
              }
            </div>
          }
          title={"Founder"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__baSku)}
            height={512 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image70LreVgxzrC}
            width={512 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Microsoft"}
          dest={
            "https://twitter.com/monirabuhilal/status/1283932117823623169" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__rn9Z
              )}
            >
              {"Monir Abu Hilal"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___25LQw
              )}
            >
              {
                "So exciting to see Plasmic announced publicly and the progress the team has made so far!\n\nA new design tool that bridges dev & design by allowing designers+engineers to create or compose existing react components visually and generate production-ready react code!"
              }
            </div>
          }
          title={"Principal Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__ppEl9)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image21Dqmr3K45D}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={null}
          dest={
            "https://twitter.com/voidwarren/status/1294366787505541120" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__iiWp
              )}
            >
              {"@voidwarren"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__kytbO
              )}
            >
              {
                "fellow UI engineers and designers, you should pay attention to what the folks over at @plasmicapp are doing. I've been using the beta and it is pretty excellent—this is certainly the future of component development."
              }
            </div>
          }
          title={null}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__qbeSs)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image31FgP35C5M}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Field Office"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__iKxX
              )}
            >
              {"Jean-Philippe Lauzon"}
            </div>
          }
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__rncH2
              )}
            >
              {
                "Simply wanted to state how impress I was with what you guys came up with. At Field Office, we've been trying to get ahead of the competition through efficiency, blazing-fast site, and outstanding design and I strongly believe your product will be of great help to move us forward in that direction."
              }
            </div>
          }
          title={"Founding Partner"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__yc2P2)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image41PGoZZ6Ey}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Whereby"}
          dest={
            "https://twitter.com/aarongarciah/status/1286420191560302598" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__zo8YY
              )}
            >
              {"Aarón García"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__oedXx
              )}
            >
              {
                "Just received my access to @plasmicapp and the onboarding tutorial is legit 👌"
              }
            </div>
          }
          title={"UI Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__nhM8R)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image442XmoUlGl}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"GoodRx"}
          dest={
            "https://twitter.com/JedBridges/status/1284204839136722944" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__yWe86
              )}
            >
              {"Jed Bridges"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___1TUyN
              )}
            >
              {
                "Got to try this out a few months ago. It’s absolutely incredible"
              }
            </div>
          }
          title={"Senior UX Designer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__riSs5)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image48MvIw252S}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Nylas"}
          dest={
            "https://twitter.com/pfista/status/1283883604011913216" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__b4Lql
              )}
            >
              {"Michael Pfister"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__f9LQr
              )}
            >
              {"Wow did Webflow and Figma just have a beautiful baby?"}
            </div>
          }
          title={"Head of Product"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__qEmdQ)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image50Tk5CdJrnd}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Supersorted.app"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__q3Yh
              )}
            >
              {"Nitin Aggarwal"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__my5E
              )}
            >
              {
                "We're totally blown away many times a day because of plasmic. You're doing god's work."
              }
            </div>
          }
          title={"Founder"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__g60)}
            height={400 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image58CTc2ZXwO}
            width={400 as const}
          />
        </Testimonial>

        <Testimonial
          company={null}
          dest={
            "https://twitter.com/i5aurabh/status/1284392576682885126" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__iNfQd
              )}
            >
              {"Saurabh Kabra"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__v9SP9
              )}
            >
              {
                "This is going to be huge. UX--> UI-->React Code. Connected to @figmadesign, now Pixels for a visual designer have much more detail, code-connect and therefore thought. Time and efforts saved. \nThe amount of faf and jibberish in product meetings will be reduced."
              }
            </div>
          }
          title={null}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__h1Si0)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image47Z7Q0WZtnF}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={null}
          dest={
            "https://twitter.com/Smartster/status/1295042723775422464" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___9XDl
              )}
            >
              {"Marcus Richmond"}
            </div>
          }
          quote={
            "I only tested the beta version of @plasmicapp for a bit and I see incredible potential in this product. Surely one, if not the top place you (Including myself) want to work at, to shape the incredible future of design and development. Current market leaders should fear this one."
          }
          title={"Product Designer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__swbXh)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image46Zfpl2P14L}
            width={48 as const}
          />
        </Testimonial>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__vV4F3)}
      >
        <Testimonial
          company={"Facebook"}
          dest={"https://twitter.com/_dte/status/1283859788372287491" as const}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__f0Hio
              )}
            >
              {"Dan Eden"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__aBtNd
              )}
            >
              {
                "I was honored to get a preview of @plasmicapp around a year ago and… wow. The progress they’ve made to bridge design & development using (and generating!) real components is super exciting."
              }
            </div>
          }
          title={"Design Systems Lead"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__iJlPx)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image26G5JsDdQkx}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"352 Inc."}
          name={"Lincoln Anderson"}
          noLink={"noLink" as const}
          quote={
            <React.Fragment>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__aixCk
                )}
              >
                {
                  "\"Some people will say that an app like Plasmic doesn’t fit into their workflow, or that they don't need it because they are perfectly happy hand-crafting boilerplate code, and so on."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__j4Qfh
                )}
              >
                <span>
                  <React.Fragment>
                    {"In my experience, these people "}
                  </React.Fragment>
                  <span style={{ fontWeight: 700 }}>
                    {"don’t know what they are missing"}
                  </span>
                  <React.Fragment>
                    {
                      ', and in a few years will have completely forgotten they ever doubted it."'
                    }
                  </React.Fragment>
                </span>
              </div>
            </React.Fragment>
          }
          title={"Associate Design Director"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___34PJv)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image29WlKi1L4Eq}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"APS Physics"}
          name={"Justin Wilkerson"}
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xq2K
              )}
            >
              <span>
                <React.Fragment>
                  {"I was pleasantly surprised and at times, "}
                </React.Fragment>
                <span style={{ fontWeight: 700 }}>{"blown away"}</span>
                <React.Fragment>
                  {
                    ", with the Plasmic approach to solving the problem. The whole concept of variants, interactive variants, and slots feels natural and intuitive."
                  }
                </React.Fragment>
              </span>
            </div>
          }
          title={"Software Developer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__gp9Jo)}
            height={420 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image32RtBuhLfpe}
            width={420 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Sutter Hill Ventures"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__iXmOv
              )}
            >
              {"Sam Pullara"}
            </div>
          }
          noLink={"noLink" as const}
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__cMsgT
              )}
            >
              {
                "Went from mock to working exported code today for this app with Plasmic. Was going to take me FOREVER to do it otherwise."
              }
            </div>
          }
          title={"Managing Director"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___2SrXf)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image24BrkhP7IR0}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Hidden Cities"}
          dest={
            "https://twitter.com/lindadong/status/1284136470677032962" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__dpF7O
              )}
            >
              {"Linda Dong"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__ef3Aa
              )}
            >
              {
                "This is what I like about this Figma to codebase tool 🥰\n\n- You can design all the UI states and screen breakpoints visually \n- You can hook up your designs to real user data\n- It’s not throwaway code that needs to be rewritten by a developer every time you change a design"
              }
            </div>
          }
          title={"Designer & Founder"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___4CxFl)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image23Sd8FqsUf}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Outdoorsy"}
          dest={"https://twitter.com/mgwut/status/1284152249917177857" as const}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wIIsm
              )}
            >
              {"Max Gustofson"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__tjoM
              )}
            >
              {
                "After using this for about an hour, I'm convinced this is the future."
              }
            </div>
          }
          title={"Design Director"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__wwPtJ)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image280CMsqtag4}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Undead Labs, Microsoft"}
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__diwKo
              )}
            >
              {"Viet Truong"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__hA2WE
              )}
            >
              {
                "In \"traditional\" software development, I've found teams are a bit accustomed to a slow handoff between design and engineering (engineers are handed photoshop/figma/sketch files and recreate things by hand). There's a huge opportunity for industry-wide impact with Plasmic."
              }
            </div>
          }
          title={"Software Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__e6Zcd)}
            height={48 as const}
            role={"img"}
            src={image25JukHnjBm2}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Instabase"}
          dest={
            "https://twitter.com/lydiagu/status/1284444591870148608" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__jd2Gn
              )}
            >
              {"Lydia Gu"}
            </div>
          }
          quote={
            "Really amazing work by the \n@plasmicapp team building a tool that seamlessly connects design and code. No more tedious back-and-worth between developers and designers on css attributes!"
          }
          title={"Software Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__nMeh6)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image279Uio4NrWb}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Software Technology Group"}
          dest={
            "https://twitter.com/javier_mora94/status/1301159659496189955" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qfcL
              )}
            >
              {"Brian Richins"}
            </div>
          }
          quote={
            "The @plasmicapp design tool is fantastic, and the tutorial is perfect. Working through the code side next and thinking this may be the way I build apps now. The team was super responsive and agile too; sent a few minor suggestions via built-in chat and they fixed stuff live🤯"
          }
          title={"Software Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__je0Xd)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image43Xlpa8IjYv}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Globant"}
          dest={
            "https://twitter.com/javier_mora94/status/1301159659496189955" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___13Ssv
              )}
            >
              {"Javier Fuentes Mora"}
            </div>
          }
          quote={
            "I have been testing @plasmicapp for the last 2 days , and I just have to say its AMAZING "
          }
          title={"Web Developer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img___7Lp2C)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={personHkxei5CPu}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Capital Rx"}
          dest={
            "https://twitter.com/thoughtntheory/status/1288567547739148288" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__pDn2J
              )}
            >
              {"Dennis Eusebio"}
            </div>
          }
          quote={
            "Trying out @plasmicapp. Tons of potential here. If you’re building a design system for your team I’d suggest giving it a look."
          }
          title={"Director of UI/UX"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__fGbK)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image45CZnS6ZLBf}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Sidecar Health"}
          dest={
            "https://twitter.com/hermano360/status/1283842550709710848" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box___8B2Kv
              )}
            >
              {"Herminio Garcia"}
            </div>
          }
          quote={
            "Really excited about this UI to React components platform. Definitely see a bright future!"
          }
          title={"Software Engineer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__fUuL5)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image51WcC99HXh}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Coupa Software"}
          dest={
            "https://twitter.com/Tony_DesignTest/status/1381200086596784131" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__c6Nh
              )}
            >
              {"Tony Key"}
            </div>
          }
          quote={
            "Plasmicapp is the most important app to be released in the last five years"
          }
          title={"Senior UX Designer"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__b2M)}
            height={211 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image57AVfwvYtpk}
            width={211 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Coinbase"}
          dest={
            "https://twitter.com/frankyoo/status/1283963068003700739" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__jfe3C
              )}
            >
              {"Frank Yoo"}
            </div>
          }
          quote={
            "One step closer to the holy grail of design tools + the benefit of more productive teams. Excited about this milestone."
          }
          title={"VP of Design & Research"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__bFrvR)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image49S6UJdcNii}
            width={48 as const}
          />
        </Testimonial>

        <Testimonial
          company={"Andreessen Horowitz"}
          dest={
            "https://twitter.com/stevesi/status/1283833356396851201" as const
          }
          name={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__wtiHh
              )}
            >
              {"Steve Sinofsky"}
            </div>
          }
          quote={
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__d2Kjc
              )}
            >
              {"Exciting work going on at Plasmic."}
            </div>
          }
          title={"Board Partner"}
        >
          <img
            alt={""}
            className={classNames(defaultcss.img, sty.img__j4IUv)}
            height={48 as const}
            loading={"lazy" as const}
            role={"img"}
            src={image52WV9THJz5J}
            width={48 as const}
          />
        </Testimonial>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestimonials__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestimonials__VariantsArgs;
    args?: PlasmicTestimonials__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTestimonials__Fetches;
  } & Omit<PlasmicTestimonials__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTestimonials__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestimonials__ArgProps,
      internalVariantPropNames: PlasmicTestimonials__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTestimonials__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestimonials";
  } else {
    func.displayName = `PlasmicTestimonials.${nodeName}`;
  }
  return func;
}

export const PlasmicTestimonials = Object.assign(
  // Top-level PlasmicTestimonials renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTestimonials
    internalVariantProps: PlasmicTestimonials__VariantProps,
    internalArgProps: PlasmicTestimonials__ArgProps
  }
);

export default PlasmicTestimonials;
/* prettier-ignore-end */
