// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ahDbvP3tQbz5L86vvqnDB6
// Component: wEWSJEhTAb3Ve8
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SectionHeading from "../../SectionHeading"; // plasmic-import: rBU-OOpjazHTmC/component
import Columns from "../../Columns"; // plasmic-import: 0CBsYTIv2rqb5s/component
import ListItem from "../../ListItem"; // plasmic-import: 94-lZb0fjQQyA/component
import YouTube from "react-youtube"; // plasmic-import: iGS-ZdT5tIqv3/codeComponent
import { GoogleMap } from "@react-google-maps/api"; // plasmic-import: wPdqALKx0zBrv/codeComponent
import { MuiSelect } from "../../../../components/MuiSelect"; // plasmic-import: sF5_3c-TMvTZn0/codeComponent
import { ButtonGroup } from "@material-ui/core"; // plasmic-import: e1GTW4GzW4JWIZ/codeComponent
import { Button } from "@material-ui/core"; // plasmic-import: mMZRNfkOFY9d6_/codeComponent
import { Slider } from "antd"; // plasmic-import: 2ywtfFl2O7i5S/codeComponent
import { Menu } from "antd"; // plasmic-import: U4nr-U7opdYxO/codeComponent
import MenuItem from "antd/lib/menu/MenuItem"; // plasmic-import: tc9INQDqcLVTV/codeComponent
import { Alert } from "antd"; // plasmic-import: 8eAFix8uprFIH/codeComponent
import { Collapse } from "antd"; // plasmic-import: ed5pFlMdA9fRA/codeComponent
import CollapsePanel from "antd/lib/collapse/CollapsePanel"; // plasmic-import: tsqckj3olOaOs/codeComponent
import { ArwesCard } from "../../../../components/Arwes"; // plasmic-import: 8nKJ1vOPqREl9Q/codeComponent
import { Text } from "@arwes/core"; // plasmic-import: ONgboqriVZ3abj/codeComponent
import { Figure } from "@arwes/core"; // plasmic-import: WBfjWPu0ZuPsEV/codeComponent
import { ProductGallery } from "../../../../components/ItemGallery"; // plasmic-import: yE3bTeDcu_Gt30/codeComponent
import { CmsGallery } from "../../../../components/ItemGallery"; // plasmic-import: VXz41ZvCgYlh8_/codeComponent
import { Reveal } from "../../../../components/Reveal"; // plasmic-import: s7BF0_pmrmF7Ns/codeComponent
import { Tilt } from "../../../../components/Tilt"; // plasmic-import: jSnfu3w8eqyB88/codeComponent
import { ParallaxWrapper } from "../../../../components/ParallaxWrapper"; // plasmic-import: JRXg9kSQr6f0Oo/codeComponent
import { Embed } from "../../../../components/Embed"; // plasmic-import: l-KMpKAkvkDEKo/codeComponent
import ColoredSection from "../../ColoredSection"; // plasmic-import: iytKPQ2Dha4EM_/component
import LinkButton from "../../LinkButton"; // plasmic-import: X-r_77142RXggy/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: XKozue_V53A-If/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_code_component_examples_primary_copy.module.css"; // plasmic-import: ahDbvP3tQbz5L86vvqnDB6/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: wEWSJEhTAb3Ve8/css

import PlasmicLogoIcon from "./icons/PlasmicIcon__PlasmicLogo"; // plasmic-import: 8NcmlLcsoVK5be/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: mcVB8NpbDSzc_5/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: 8SafvFIcyC-6nl/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: aUptDMAvdZIZeC/icon
import Icon8Icon from "../plasmic_kit_website_components/icons/PlasmicIcon__Icon8"; // plasmic-import: f4GO4W3yZm/icon
import image0Gb9W4LAu535Pd from "./images/image.png"; // plasmic-import: 0gb9w4LAu535PD/picture
import image1514V5EadAaRPkmx from "./images/image15.png"; // plasmic-import: 14v5EadAaRPkmx/picture
import image6BZGe1W3S8UhL1C from "./images/image6.png"; // plasmic-import: bZGe1W3S8UhL1c/picture
import image5C44Fy5Cn0DIj6A from "./images/image5.png"; // plasmic-import: c44fy5CN0dIJ6a/picture
import image7IwMdxU8DojUhC from "./images/image7.png"; // plasmic-import: IWMdx-U8DOJUhC/picture
import image8Sr99Zj1Z3G9Yj from "./images/image8.png"; // plasmic-import: SR99ZJ1z_3G9Yj/picture
import image14KelElE7BNg5T0 from "./images/image14.svg"; // plasmic-import: -KelElE7bNg5t0/picture

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  sectionHeading?: p.Flex<typeof SectionHeading>;
  columns?: p.Flex<typeof Columns>;
  arwesCard?: p.Flex<typeof ArwesCard>;
  h1?: p.Flex<"h1">;
  arwesFigure?: p.Flex<typeof Figure>;
  productGallery?: p.Flex<typeof ProductGallery>;
  cmsGallery?: p.Flex<typeof CmsGallery>;
  reveal?: p.Flex<typeof Reveal>;
  tilt?: p.Flex<typeof Tilt>;
  embed?: p.Flex<typeof Embed>;
  coloredSection?: p.Flex<typeof ColoredSection>;
  linkButton?: p.Flex<typeof LinkButton>;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  dataFetches?: PlasmicHome__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.box__whgzO)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__w5IT4)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__mrjhr)}
              >
                <a
                  className={classNames(defaultcss.all, sty.link__fdyRg)}
                  href={"https://www.plasmic.app" as const}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__hsH9D)}
                    height={320 as const}
                    role={"img"}
                    src={image0Gb9W4LAu535Pd}
                    width={912 as const}
                  />
                </a>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__fi4Q)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__nuRqE
                  )}
                >
                  {"Page builder, meet code components."}
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__qL5)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__eKpqv
                    )}
                  >
                    <span>
                      <React.Fragment>{"Introducing "}</React.Fragment>
                      <span style={{ fontWeight: 700 }}>{"Plasmic 2.0"}</span>
                      <React.Fragment>
                        {
                          ": the web design tool that integrates seamlessly with your codebase and lets you drag-and-drop your real production React components."
                        }
                      </React.Fragment>
                    </span>
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__mPPj6
                    )}
                  >
                    {
                      "Empower your team with your design system, interactive components, production data, and much more."
                    }
                  </div>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__ujjUr)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__xtuYh)}
                  height={596 as const}
                  role={"img"}
                  src={image1514V5EadAaRPkmx}
                  width={1016 as const}
                />

                <a
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.link__g7OCa
                  )}
                  href={"https://plasmic.app/proj/code-components" as const}
                  target={"_blank" as const}
                >
                  {"Edit this page in Plasmic!"}
                </a>
              </p.Stack>
            </p.Stack>
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box___1J45S)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__oDaT6)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__euMmd)}
              >
                <SectionHeading
                  data-plasmic-name={"sectionHeading"}
                  data-plasmic-override={overrides.sectionHeading}
                  className={classNames("__wab_instance", sty.sectionHeading)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__geF2R
                  )}
                >
                  {
                    "Tap into the full universe of open-source npm libraries. Or expose components from your own codebase."
                  }
                </div>
              </p.Stack>

              <Columns
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                className={classNames("__wab_instance", sty.columns)}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box___60Yvy)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__oe8Xw)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box___6Lq)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__wksDl)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__tvEao
                      )}
                    >
                      {"Bring any design system."}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__dtx5V
                      )}
                    >
                      {
                        "Use your own design system, or use off-the-shelf libraries complete with all the theming and customizations you've applied in your codebase. Seamlessly interweave Plasmic-designed content and code components."
                      }
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___9EyCf
                      )}
                    >
                      {"Roboto"}
                    </div>
                  </p.Stack>
                </p.Stack>

                <ListItem
                  _package={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__dqkre
                      )}
                    >
                      {"@material-ui/core"}
                    </div>
                  }
                  className={classNames("__wab_instance", sty.listItem__gfKlI)}
                  title={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__dUNwI
                      )}
                    >
                      {"Material UI"}
                    </div>
                  }
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__r9WiL)}
                  >
                    <MuiSelect
                      className={classNames(
                        "__wab_instance",
                        sty.muiSelect__wsZ6M
                      )}
                      label={"Delivery method" as const}
                      options={[
                        { value: "standard", label: "Standard Shipping" },
                        { value: "expedited", label: "Expedited Shipping" },
                        { value: "sameday", label: "Same-Day Delivery" },
                        { value: "pickup", label: "Scheduled Pickup" }
                      ]}
                    />

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__tkSyG)}
                    >
                      <ButtonGroup
                        className={classNames(
                          "__wab_instance",
                          sty.muiButtonGroup__vl8N
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton___9Df22
                          )}
                        >
                          {"md"}
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton__xuRq7
                          )}
                        >
                          {"lg"}
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton___0VWf7
                          )}
                        >
                          {"xl"}
                        </Button>

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.muiButton__nQms4
                          )}
                        >
                          {"xxl"}
                        </Button>
                      </ButtonGroup>
                    </p.Stack>
                  </p.Stack>
                </ListItem>

                {false ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__e0Gd)}
                  >
                    <ListItem
                      _package={"@material-ui/core"}
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__lUYva
                      )}
                      title={"Material UI Select"}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__g5W71)}
                      >
                        <MuiSelect
                          className={classNames(
                            "__wab_instance",
                            sty.muiSelect__jymm6
                          )}
                          label={"Delivery method" as const}
                          options={[
                            { value: "standard", label: "Standard Shipping" },
                            { value: "expedited", label: "Expedited Shipping" },
                            { value: "sameday", label: "Same-Day Delivery" },
                            { value: "pickup", label: "Scheduled Pickup" }
                          ]}
                        />
                      </p.Stack>
                    </ListItem>

                    <ListItem
                      _package={"@material-ui/core"}
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__c667
                      )}
                      title={"Material UI Button Group"}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__hUIiP)}
                      >
                        <ButtonGroup
                          className={classNames(
                            "__wab_instance",
                            sty.muiButtonGroup__jNug
                          )}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton__hnbFf
                            )}
                          >
                            {"md"}
                          </Button>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton__iHcxK
                            )}
                          >
                            {"lg"}
                          </Button>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton__i0Ypk
                            )}
                          >
                            {"xl"}
                          </Button>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.muiButton__kdtw2
                            )}
                          >
                            {"xxl"}
                          </Button>
                        </ButtonGroup>
                      </p.Stack>
                    </ListItem>
                  </p.Stack>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__oEh97)}
                  >
                    <ListItem
                      _package={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__updtz
                          )}
                        >
                          {"antd"}
                        </div>
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__pe6F
                      )}
                      title={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__uhaXo
                          )}
                        >
                          {"Ant Design"}
                        </div>
                      }
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__wm9Ji)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.box__i8MY)}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.box__ssSnj
                            )}
                          >
                            <Slider
                              className={classNames(
                                "__wab_instance",
                                sty.slider___5N9IZ
                              )}
                              range={true}
                            />

                            <Menu
                              className={classNames(
                                "__wab_instance",
                                sty.menu___0UQsu
                              )}
                              defaultSelectedKeys={["opt3"]}
                            >
                              <MenuItem
                                className={classNames(
                                  "__wab_instance",
                                  sty.menuItem__lzv10
                                )}
                                key={"opt1" as const}
                              >
                                {"Home"}
                              </MenuItem>

                              <MenuItem
                                className={classNames(
                                  "__wab_instance",
                                  sty.menuItem__ykyeD
                                )}
                                key={"opt2" as const}
                              >
                                {"Features"}
                              </MenuItem>

                              <MenuItem
                                className={classNames(
                                  "__wab_instance",
                                  sty.menuItem__kdmYb
                                )}
                                key={"opt3" as const}
                              >
                                {"Case studies"}
                              </MenuItem>
                            </Menu>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.box__cUrxa
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                sty.box__thIhe
                              )}
                            >
                              <Alert
                                className={classNames(
                                  "__wab_instance",
                                  sty.alert___030Jh
                                )}
                                description={
                                  <div
                                    className={classNames(
                                      defaultcss.all,
                                      sty.box__xy63R
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.box__k5EMk
                                      )}
                                    >
                                      {"Thank you for your order! "}
                                    </div>

                                    <PlasmicLogoIcon
                                      className={classNames(
                                        defaultcss.all,
                                        sty.svg___7Su8Q
                                      )}
                                      role={"img"}
                                    />
                                  </div>
                                }
                                message={"Purchase complete" as const}
                                showIcon={true}
                                type={"success" as const}
                              />

                              <Alert
                                className={classNames(
                                  "__wab_instance",
                                  sty.alert__fyWbQ
                                )}
                                description={"Please fill all required fields."}
                                message={"Error submitting form" as const}
                                showIcon={true}
                                type={"error" as const}
                              />
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                sty.box__m8XY3
                              )}
                            >
                              <Collapse
                                className={classNames(
                                  "__wab_instance",
                                  sty.collapse__gsKv4
                                )}
                                defaultActiveKey={["1"]}
                              >
                                <CollapsePanel
                                  className={classNames(
                                    "__wab_instance",
                                    sty.collapsePanel__vmHsq
                                  )}
                                  header={"Shipping" as const}
                                  key={"1" as const}
                                >
                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      defaultcss.all,
                                      sty.box__wslds
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.box__bsShf
                                      )}
                                    >
                                      {"Standard shipping"}
                                    </div>

                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.box__cY8J
                                      )}
                                    >
                                      {"2 South Park\nSan Francisco, CA 94107"}
                                    </div>

                                    <a
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.link__fOx77
                                      )}
                                      href={"#" as const}
                                    >
                                      {"Change"}
                                    </a>
                                  </p.Stack>
                                </CollapsePanel>

                                <CollapsePanel
                                  className={classNames(
                                    "__wab_instance",
                                    sty.collapsePanel__d9Po8
                                  )}
                                  header={"Payment method" as const}
                                  key={"2" as const}
                                >
                                  <p.Stack
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      defaultcss.all,
                                      sty.box___018VE
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.box__xFyha
                                      )}
                                    >
                                      {"Using gift card balance."}
                                    </div>

                                    <a
                                      className={classNames(
                                        defaultcss.all,
                                        defaultcss.__wab_text,
                                        sty.link__qyZmp
                                      )}
                                      href={"#" as const}
                                    >
                                      {"Change"}
                                    </a>
                                  </p.Stack>
                                </CollapsePanel>
                              </Collapse>
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </div>
                    </ListItem>
                  </p.Stack>
                ) : null}
                {false ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__g2Usa)}
                  >
                    <ListItem
                      _package={"antd"}
                      className={classNames(
                        "__wab_instance",
                        sty.listItem___0Cmr
                      )}
                      title={"Ant Slider"}
                    >
                      <Slider
                        className={classNames(
                          "__wab_instance",
                          sty.slider__hvokU
                        )}
                        range={true}
                      />
                    </ListItem>

                    <ListItem
                      _package={"antd"}
                      className={classNames(
                        "__wab_instance",
                        sty.listItem__xQkQh
                      )}
                      title={"Ant Menu"}
                    >
                      <Menu
                        className={classNames(
                          "__wab_instance",
                          sty.menu__hgQaL
                        )}
                      >
                        <MenuItem
                          className={classNames(
                            "__wab_instance",
                            sty.menuItem__kosO
                          )}
                          key={"opt1" as const}
                        >
                          {"Home"}
                        </MenuItem>

                        <MenuItem
                          className={classNames(
                            "__wab_instance",
                            sty.menuItem__sEai
                          )}
                          key={"opt2" as const}
                        >
                          {"Features"}
                        </MenuItem>

                        <MenuItem
                          className={classNames(
                            "__wab_instance",
                            sty.menuItem__mpslk
                          )}
                          key={"opt3" as const}
                        >
                          {"Case studies"}
                        </MenuItem>
                      </Menu>
                    </ListItem>
                  </p.Stack>
                ) : null}
                {false ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box___29FcT)}
                  >
                    <ListItem
                      _package={"antd"}
                      className={classNames(
                        "__wab_instance",
                        sty.listItem___7IDnM
                      )}
                      title={"Ant Alert"}
                    >
                      <Alert
                        className={classNames(
                          "__wab_instance",
                          sty.alert__bTqTy
                        )}
                        description={
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.box___7QBju
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__i0EtB
                              )}
                            >
                              {"Thank you for your order! "}
                            </div>

                            <PlasmicLogoIcon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__ur6D2
                              )}
                              role={"img"}
                            />
                          </div>
                        }
                        message={"Purchase complete" as const}
                        showIcon={true}
                      />

                      <Alert
                        className={classNames(
                          "__wab_instance",
                          sty.alert__uwHbj
                        )}
                        description={"Please fill all required fields."}
                        message={"Error submitting form" as const}
                        showIcon={true}
                      />
                    </ListItem>

                    <ListItem
                      _package={"antd"}
                      className={classNames(
                        "__wab_instance",
                        sty.listItem___6V9K9
                      )}
                      title={"Ant Collapse"}
                    >
                      <Collapse
                        className={classNames(
                          "__wab_instance",
                          sty.collapse__cTvcc
                        )}
                      >
                        <CollapsePanel
                          className={classNames(
                            "__wab_instance",
                            sty.collapsePanel__fn5Sb
                          )}
                          header={"Shipping" as const}
                          key={"1" as const}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.box__lA1Hx
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box___4Cbwf
                              )}
                            >
                              {"Standard shipping"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__heYCv
                              )}
                            >
                              {"2 South Park\nSan Francisco, CA 94107"}
                            </div>

                            <a
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.link__kjLgw
                              )}
                              href={"#" as const}
                            >
                              {"Change"}
                            </a>
                          </p.Stack>
                        </CollapsePanel>

                        <CollapsePanel
                          className={classNames(
                            "__wab_instance",
                            sty.collapsePanel__ck0Ba
                          )}
                          header={"Payment method" as const}
                          key={"2" as const}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              defaultcss.all,
                              sty.box__aYmrs
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__rPkKo
                              )}
                            >
                              {"Using gift card balance."}
                            </div>

                            <a
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.link__z2Uhz
                              )}
                              href={"#" as const}
                            >
                              {"Change"}
                            </a>
                          </p.Stack>
                        </CollapsePanel>
                      </Collapse>
                    </ListItem>
                  </p.Stack>
                ) : null}
              </p.Stack>

              <div className={classNames(defaultcss.all, sty.box__hHKoO)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box___3GJqW)}
                >
                  <ListItem
                    _package={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__rWa6B
                        )}
                      >
                        {"@arwes/core"}
                      </div>
                    }
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__oEtwS
                    )}
                    title={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__xcOmG
                        )}
                      >
                        {"Arwes Card"}
                      </div>
                    }
                  >
                    <div className={classNames(defaultcss.all, sty.box__tb1Be)}>
                      <ArwesCard
                        data-plasmic-name={"arwesCard"}
                        data-plasmic-override={overrides.arwesCard}
                        caption={"Photo of the Orion nebula taken by Hubble."}
                        className={classNames("__wab_instance", sty.arwesCard)}
                        title={true ? "Nebula" : null}
                      >
                        <div
                          className={classNames(defaultcss.all, sty.box___2ADg)}
                        >
                          <Text
                            as={"h1" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.arwesText__llKms
                            )}
                          >
                            {true ? (
                              <h1
                                data-plasmic-name={"h1"}
                                data-plasmic-override={overrides.h1}
                                className={classNames(
                                  defaultcss.h1,
                                  defaultcss.__wab_text,
                                  sty.h1
                                )}
                              >
                                {"NEBULA"}
                              </h1>
                            ) : null}
                          </Text>

                          <Text
                            as={"p" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.arwesText__fqNck
                            )}
                          >
                            {
                              "A nebula is an interstellar cloud of dust, hydrogen, helium and other ionized gases. Originally, the term was used to describe any diffused astronomical object, including galaxies beyond the Milky Way."
                            }
                          </Text>

                          <Figure
                            data-plasmic-name={"arwesFigure"}
                            data-plasmic-override={overrides.arwesFigure}
                            alt={"Orion" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.arwesFigure
                            )}
                            src={
                              "https://playground.arwes.dev/assets/images/wallpaper.jpg" as const
                            }
                          >
                            {"Photo of the Orion nebula taken by Hubble."}
                          </Figure>
                        </div>
                      </ArwesCard>
                    </div>
                  </ListItem>
                </p.Stack>
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__f632)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__oJcFi)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__qHgn
                  )}
                >
                  {"Access your real production data."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__nY51A
                  )}
                >
                  {
                    "Bring components of any complexity—components that fetch data, use application/session state, and more."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__yUcsM)}
              >
                <ListItem
                  _package={null}
                  className={classNames("__wab_instance", sty.listItem__dctDp)}
                  title={
                    "Data from Shopify product catalog (via Storefront GraphQL API)"
                  }
                >
                  <ProductGallery
                    data-plasmic-name={"productGallery"}
                    data-plasmic-override={overrides.productGallery}
                    className={classNames("__wab_instance", sty.productGallery)}
                    scroller={true}
                  />
                </ListItem>
              </p.Stack>

              <ListItem
                _package={null}
                className={classNames("__wab_instance", sty.listItem__vo5MH)}
                title={"Data from Contentful CMS (via REST API)"}
              >
                <div className={classNames(defaultcss.all, sty.box__jdzvs)}>
                  <CmsGallery
                    data-plasmic-name={"cmsGallery"}
                    data-plasmic-override={overrides.cmsGallery}
                    className={classNames("__wab_instance", sty.cmsGallery)}
                    scroller={true}
                  />
                </div>
              </ListItem>
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.box__r4Epo)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__rq75X)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__aLsY1)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__cBrry
                    )}
                  >
                    {"Extend Plasmic with any interaction."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ha70G
                    )}
                  >
                    {
                      "You can introduce some very general-purpose building blocks that extend Plasmic's feature set."
                    }
                  </div>
                </p.Stack>

                <ListItem
                  _package={"react-reveal"}
                  className={classNames("__wab_instance", sty.listItem__dyIsZ)}
                  title={"Reveal on scroll"}
                >
                  <div className={classNames(defaultcss.all, sty.box__b64Gw)}>
                    <Reveal
                      data-plasmic-name={"reveal"}
                      data-plasmic-override={overrides.reveal}
                      cascade={true}
                      className={classNames("__wab_instance", sty.reveal)}
                      direction={"up" as const}
                      effect={"fade" as const}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__q9GgG)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__xp1Xh
                          )}
                        >
                          {"JAY-Z"}
                        </div>
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___1PUsa)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__odZpt
                          )}
                        >
                          {"FOLLOW ARTIST"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.box__t1Mo)}
                        >
                          <a
                            className={classNames(
                              defaultcss.all,
                              sty.link___6Kh1Z
                            )}
                            href={"https://www.facebook.com/JayZ" as const}
                            target={"_blank" as const}
                          >
                            <IconIcon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__weIno
                              )}
                              role={"img"}
                            />
                          </a>

                          <a
                            className={classNames(
                              defaultcss.all,
                              sty.link___81M0A
                            )}
                            href={"https://twitter.com/sc?lang=en" as const}
                            target={"_blank" as const}
                          >
                            <Icon2Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__ybis4
                              )}
                              role={"img"}
                            />
                          </a>

                          <a
                            className={classNames(
                              defaultcss.all,
                              sty.link__qSpQ
                            )}
                            href={"https://lifeandtimes.com/" as const}
                            target={"_blank" as const}
                          >
                            <Icon3Icon
                              className={classNames(
                                defaultcss.all,
                                sty.svg__zassJ
                              )}
                              role={"img"}
                            />
                          </a>
                        </p.Stack>
                      </p.Stack>
                    </Reveal>
                  </div>
                </ListItem>

                <ListItem
                  _package={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__gKkNu
                      )}
                    >
                      {"react-parallax-tilt"}
                    </div>
                  }
                  className={classNames("__wab_instance", sty.listItem__svrXw)}
                  title={"3D parallax tilt effect"}
                >
                  <div className={classNames(defaultcss.all, sty.box__vacF)}>
                    <Tilt
                      data-plasmic-name={"tilt"}
                      data-plasmic-override={overrides.tilt}
                      className={classNames("__wab_instance", sty.tilt)}
                      reset={false}
                      tiltReverse={true}
                      trackOnWindow={false}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__aJLhM)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.box__m1RiF,
                            hasVariant(globalVariants, "screen", "mobile")
                              ? ("inner-element" as const)
                              : ("inner-element" as const)
                          )}
                        />
                      </div>
                    </Tilt>
                  </div>
                </ListItem>

                <ListItem
                  _package={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__x6Vgp
                      )}
                    >
                      {"react-scroll-parallax"}
                    </div>
                  }
                  className={classNames("__wab_instance", sty.listItem__gVim8)}
                  title={"Parallax scroll effect"}
                >
                  <div className={classNames(defaultcss.all, sty.box__dAlE)}>
                    <div className={classNames(defaultcss.all, sty.box__w0W43)}>
                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax__bPt4B
                        )}
                        y={[-20, 20]}
                      >
                        <img
                          alt={"" as const}
                          className={classNames(defaultcss.img, sty.img__jqFj)}
                          height={1251 as const}
                          loading={"lazy" as const}
                          role={"img"}
                          src={image6BZGe1W3S8UhL1C}
                          width={1001 as const}
                        />
                      </ParallaxWrapper>

                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax__cGDb3
                        )}
                        y={[40, -40]}
                      >
                        <img
                          alt={""}
                          className={classNames(defaultcss.img, sty.img__cvLHd)}
                          height={1251 as const}
                          loading={"lazy" as const}
                          role={"img"}
                          src={image5C44Fy5Cn0DIj6A}
                          width={1001 as const}
                        />
                      </ParallaxWrapper>

                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax__t7R9
                        )}
                        y={[-20, 20]}
                      >
                        <img
                          alt={""}
                          className={classNames(defaultcss.img, sty.img__tUJp9)}
                          height={492 as const}
                          loading={"lazy" as const}
                          role={"img"}
                          src={image7IwMdxU8DojUhC}
                          width={875 as const}
                        />
                      </ParallaxWrapper>

                      <ParallaxWrapper
                        className={classNames(
                          "__wab_instance",
                          sty.parallax__jMrFu
                        )}
                        y={[99, -99]}
                      >
                        <img
                          alt={""}
                          className={classNames(defaultcss.img, sty.img__sa1M)}
                          height={1093 as const}
                          loading={"lazy" as const}
                          role={"img"}
                          src={image8Sr99Zj1Z3G9Yj}
                          width={660 as const}
                        />
                      </ParallaxWrapper>
                    </div>
                  </div>
                </ListItem>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__mzp0R)}
                >
                  <ListItem
                    _package={null}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__o0Mag
                    )}
                    title={'A generic "Embed Code" component'}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__vc7LS)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__yHyHi)}
                      >
                        <Embed
                          data-plasmic-name={"embed"}
                          data-plasmic-override={overrides.embed}
                          className={classNames("__wab_instance", sty.embed)}
                          code={
                            '<a class="twitter-timeline" href="https://twitter.com/plasmicapp?ref_src=twsrc%5Etfw">Tweets by plasmicapp</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>' as const
                          }
                        />
                      </div>
                    </p.Stack>
                  </ListItem>
                </p.Stack>
              </p.Stack>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__ipzTv)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__r5Gld
                )}
              >
                {"How does this work?"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__cwRfR
                )}
              >
                <span>
                  <React.Fragment>
                    {
                      "Plasmic is a page builder and design tool that has a kernel which "
                    }
                  </React.Fragment>
                  <span style={{ fontStyle: "italic" }}>
                    {"runs from within your application"}
                  </span>
                  <React.Fragment>
                    {
                      '. We call the Plasmic project "hosted" by your application.'
                    }
                  </React.Fragment>
                </span>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__baF6S
                )}
              >
                {
                  "This tight integration is what lets you easily and seamlessly expose code components of arbitrary complexity. They can connect to your application state, fetch data, implement complex behavior, and much more. All without bundling shenanigans."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__rie6W
                )}
              >
                {
                  "You can set the app host to be your localhost dev server (complete with hot reload working!) OR your actual production site."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__z57Oe
                )}
              >
                <span>
                  <span style={{ fontWeight: 700 }}>
                    {"What does it take to enable this for your codebase? "}
                  </span>
                  <React.Fragment>
                    {
                      "Simply add a snippet of code, and now you can configure any Plasmic project to use your application URL as the host. Then expose any component by calling registerComponent() on it. That's it!"
                    }
                  </React.Fragment>
                </span>
              </div>

              <a
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.link__tCzy2
                )}
                href={
                  "https://docs.plasmic.app/learn/code-components/" as const
                }
                target={"_blank" as const}
              >
                {"See developer docs ->"}
              </a>

              <a
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.link___0OGxf
                )}
                href={"https://github.com/plasmicapp/code-components" as const}
                target={"_blank" as const}
              >
                {"See this project's host repo on GitHub ->"}
              </a>
            </p.Stack>

            <ColoredSection
              data-plasmic-name={"coloredSection"}
              data-plasmic-override={overrides.coloredSection}
              className={classNames("__wab_instance", sty.coloredSection)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__tIdw)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__nfnUu
                  )}
                >
                  {
                    "Plasmic lets anyone build and deploy visual content—from full pages to sections of pages—within any tech stack."
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__nPjy2
                  )}
                >
                  {
                    "Plasmic powers some of the largest websites in the world. Companies from boutique brands to Fortune 500s use Plasmic to eliminate swaths of development work and let marketing and design teams iterate incredibly fast."
                  }
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__kipwI
                  )}
                >
                  {
                    "And now with code components, developers can equip their whole team with the exact right set of building blocks to move even faster."
                  }
                </div>

                <LinkButton
                  data-plasmic-name={"linkButton"}
                  data-plasmic-override={overrides.linkButton}
                  className={classNames("__wab_instance", sty.linkButton)}
                  href={"https://studio.plasmic.app/signup" as const}
                  icon={
                    <Icon8Icon
                      className={classNames(defaultcss.all, sty.svg___59Ikk)}
                      role={"img"}
                    />
                  }
                  label={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___9SUmm
                      )}
                    >
                      {"Try Plasmic for free"}
                    </div>
                  }
                  type={["white", "rightIcon"]}
                />

                <div className={classNames(defaultcss.all, sty.box__kqmcB)} />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__dwZ7
                  )}
                >
                  {
                    "Code components are just the beginning of what application hosting unlocks."
                  }
                </div>

                <p.Stack
                  as={"a"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.link__g9Eeb)}
                  href={"https://twitter.com/plasmicapp" as const}
                  target={"_blank" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__gV6Ly
                    )}
                  >
                    {"Follow @plasmicapp on Twitter to see what's next."}
                  </div>
                </p.Stack>

                <a
                  className={classNames(defaultcss.all, sty.link__wZal)}
                  href={"https://www.plasmic.app" as const}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___1ZeX1)}
                    height={105 as const}
                    loading={"lazy" as const}
                    role={"img"}
                    src={image14KelElE7BNg5T0}
                    width={300 as const}
                  />
                </a>
              </p.Stack>
            </ColoredSection>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sectionHeading",
    "columns",
    "arwesCard",
    "h1",
    "arwesFigure",
    "productGallery",
    "cmsGallery",
    "reveal",
    "tilt",
    "embed",
    "coloredSection",
    "linkButton"
  ],
  sectionHeading: ["sectionHeading"],
  columns: ["columns"],
  arwesCard: ["arwesCard", "h1", "arwesFigure"],
  h1: ["h1"],
  arwesFigure: ["arwesFigure"],
  productGallery: ["productGallery"],
  cmsGallery: ["cmsGallery"],
  reveal: ["reveal"],
  tilt: ["tilt"],
  embed: ["embed"],
  coloredSection: ["coloredSection", "linkButton"],
  linkButton: ["linkButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  sectionHeading: typeof SectionHeading;
  columns: typeof Columns;
  arwesCard: typeof ArwesCard;
  h1: "h1";
  arwesFigure: typeof Figure;
  productGallery: typeof ProductGallery;
  cmsGallery: typeof CmsGallery;
  reveal: typeof Reveal;
  tilt: typeof Tilt;
  embed: typeof Embed;
  coloredSection: typeof ColoredSection;
  linkButton: typeof LinkButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHome__Fetches;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sectionHeading: makeNodeComponent("sectionHeading"),
    columns: makeNodeComponent("columns"),
    arwesCard: makeNodeComponent("arwesCard"),
    h1: makeNodeComponent("h1"),
    arwesFigure: makeNodeComponent("arwesFigure"),
    productGallery: makeNodeComponent("productGallery"),
    cmsGallery: makeNodeComponent("cmsGallery"),
    reveal: makeNodeComponent("reveal"),
    tilt: makeNodeComponent("tilt"),
    embed: makeNodeComponent("embed"),
    coloredSection: makeNodeComponent("coloredSection"),
    linkButton: makeNodeComponent("linkButton"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
